Fix scheduled task time error
The server was running on development computer before the night when
local time changes from summertime to wintertime and the following error
appeared several times:

WARN server::scheduled_tasks: Sleep until failed.
Error: Sleep until next run of scheduled tasks failed
├╴at crates/server/src/scheduled_tasks.rs:96:14
│
╰─▶ Creating tomorrow's target date time failed
    ╰╴at crates/server/src/scheduled_tasks.rs:96:14

This commit changes the sleep until code to use UTC time which most
likely prevents the error.

Most likely also changing the code to use DateTime<FixedOffset> would
have fixed the issue.